#!/bin/bash
set -vx

#NODE_VERSION=$(echo $DOCKER_TAG | cut -d "-" -f2)
QEMUVER=$(echo $DOCKER_TAG)
DockerServerVersion=$(docker info --format '{{.ServerVersion}}')
DockerSxperimental=$(docker info --format '{{.ExperimentalBuild}}')

#https://stackoverflow.com/questions/60080264/docker-cannot-build-multi-platform-images-with-docker-buildx
#https://github.com/docker/buildx#installing
###export DOCKER_BUILDKIT=1
##export DOCKER_BUILDKIT=1
#docker build --platform=local -o . git://github.com/docker/buildx
##docker build -o . git://github.com/docker/buildx

#HFILE=buildx HASHcmd=sha256sum HASHSUM=3f4e77686659766a0726b5a47a87e2cc14c86ebf15abf7f19c45d23b0daff222 HURL=https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
HFILE=buildx HASHcmd=sha256sum HASHSUM=760e36543c3a2db2d61f6e2bd9c25a6a54df638726c3d4d32c6ead99680da7d7 HURL=https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64
printf "HFILE=$HFILE HASHcmd=$HASHcmd HASHSUM=$HASHSUM HURL=$HURL"
curl -o $HFILE -LR -C- -f -S --connect-timeout 15 --max-time 600 --retry 3 --dump-header - --compressed --verbose $HURL ; (printf %b CHECKSUM\\072\\040expect\\040this\\040$HASHcmd\\072\\040$HASHSUM\\040\\052$HFILE\\012 ; printf %b $HASHSUM\\040\\052$HFILE\\012 | $HASHcmd -c - ;) || (printf %b ERROR\\072\\040CHECKSUMFAILD\\072\\040the\\040file\\040has\\040this\\040$HASHcmd\\072\\040 ; $HASHcmd -b $HFILE ; exit 1)

#curl -o $HFILE -LR -C- -# -f -S --connect-timeout 15 --max-time 600 --retry 3 --retry-connrefused --dump-header --verbose https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
# curl: option --retry-connrefused: is unknown
# --progress-bar # --max-time 60 --fail-early --http1.0 --http1.1 --http2


#curl -o $HFILE -# -f -S -L --connect-timeout 15 -m 20 --retry 3 --head https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
#HFILE=buildx HASHcmd=sha256sum HASHSUM=3f4e77686659766a0726b5a47a87e2cc14c86ebf15abf7f19c45d23b0daff222 ; (printf %b $HASHSUM\\040\\052$HFILE\\012 ; printf %b $HASHSUM\\040\\052$HFILE\\012 | $HASHcmd -c - ;) || $HASHcmd -b $HFILE

mkdir -p ~/.docker/cli-plugins
mv $HFILE ~/.docker/cli-plugins/docker-buildx
chmod 755 ~/.docker/cli-plugins/docker-buildx

#docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
##docker build --no-cache --progress=plain
#docker buildx rm builder
#docker buildx create --name builder --driver docker-container --use
#docker buildx inspect --bootstrap
#docker buildx ls

  # Instantiate docker buildx builder with multi-architecture support.
  ###export DOCKER_CLI_EXPERIMENTAL=enabled
  docker -v
  docker --help || docker -h
  docker version
  docker buildx create --name mybuilder
  docker buildx use mybuilder
  # Start up buildx and verify that all is OK.
  docker buildx inspect --bootstrap

if [ $DOCKER_TAG == "latest" ]
then
  #docker build . --build-arg QEMUVER=${DOCKER_TAG} -t ${IMAGE_NAME}
  #docker buildx build . --build-arg QEMUVER=${DOCKER_TAG} -t ${IMAGE_NAME}
  #docker buildx build --tag ${IMAGE_NAME} .
  docker build --tag ${IMAGE_NAME} . || docker build .
else
  #docker build . --build-arg NODE_VERSION=${NODE_VERSION} -t ${IMAGE_NAME}
  #docker build . --build-arg QEMUVER=${DOCKER_TAG} -t ${IMAGE_NAME}
  #docker buildx build . --build-arg QEMUVER=${DOCKER_TAG} -t ${IMAGE_NAME}
  #docker buildx build . -t ${IMAGE_NAME}
  #docker buildx build --tag ${IMAGE_NAME} .
  docker build --tag ${IMAGE_NAME} . || docker build .
fi
