#!/bin/bash
set -vx

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes || docker run --rm --privileged multiarch/qemu-user-static --reset

docker buildx create \
	--name builder \
	--driver docker-container \
	--use
# 	--platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6 \	
docker buildx inspect --bootstrap
docker buildx inspect --bootstrap
